apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets
  namespace: demo
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 8f02fd1b-e213-414f-8294-36d3f5468fd0
    keyvaultName: kv-aks-demo-nvvu
    tenantId: 2c6ae73c-fd31-4e4a-88fc-24bcfcb2f5d0
    objects: |
      array:
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
  secretObjects:
    - secretName: kv-secret-sync
      type: Opaque
      data:
        - objectName: db-user
          key: db-user
        - objectName: db-password
          key: db-password
