apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets
  namespace: demo
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: kv-aks-demo-nvvu
    tenantId: 2f173612-6f45-4520-9df8-32d7ba5f2c44
    userAssignedIdentityID: 8dcc924d-7861-45bf-b0b6-3ecb11067964
    objects: |
      array:
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
  secretObjects:
    - secretName: kv-secret-sync
      type: Opaque
      data:
        - objectName: db-user
          key: db-user
        - objectName: db-password
          key: db-password
